// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('addition and substraction test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('addition and substraction test', async function() {
    await driver.get("https://safatelli.github.io/tp-test-logiciel/assets/calc.html")
    await driver.manage().window().setRect({ width: 784, height: 816 })
    await driver.findElement(By.id("num1")).click()
    await driver.findElement(By.id("num1")).sendKeys("3")
    await driver.findElement(By.id("operator")).click()
    {
      const dropdown = await driver.findElement(By.id("operator"))
      await dropdown.findElement(By.xpath("//option[. = '+']")).click()
    }
    await driver.findElement(By.id("num2")).click()
    await driver.findElement(By.id("num2")).sendKeys("4")
    await driver.findElement(By.css("html")).click()
    await driver.findElement(By.css("button")).click()
    assert(await driver.findElement(By.id("result")).getText() == "Résultat : 7")
    await driver.findElement(By.id("operator")).click()
    {
      const dropdown = await driver.findElement(By.id("operator"))
      await dropdown.findElement(By.xpath("//option[. = '-']")).click()
    }
    await driver.findElement(By.css("button")).click()
    assert(await driver.findElement(By.id("result")).getText() == "Résultat : -1")
  })
})
