// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe(' additional pages test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it(' additional pages test', async function() {
    // Test name:  additional pages test
    // Step # | name | target | value
    // 1 | open | https://www.demoblaze.com/ | 
    await driver.get("https://www.demoblaze.com/")
    // 2 | setWindowSize | 784x816 | 
    await driver.manage().window().setRect({ width: 784, height: 816 })
    // 3 | click | css=.active > .nav-link | 
    await driver.findElement(By.css(".active > .nav-link")).click()
    // 4 | assertElementPresent | id=cat | 
    {
      const elements = await driver.findElements(By.id("cat"))
      assert(elements.length)
    }
    // 5 | click | linkText=Contact | 
    await driver.findElement(By.linkText("Contact")).click()
    // 6 | assertText | id=exampleModalLabel | New message
    assert(await driver.findElement(By.id("exampleModalLabel")).getText() == "New message")
    // 7 | click | css=#exampleModal .btn-secondary | 
    await driver.findElement(By.css("#exampleModal .btn-secondary")).click()
    // 8 | click | linkText=About us | 
    await driver.findElement(By.linkText("About us")).click()
    // 9 | assertText | id=videoModalLabel | About us
    assert(await driver.findElement(By.id("videoModalLabel")).getText() == "About us")
    // 10 | click | css=#videoModal .modal-header span | 
    await driver.findElement(By.css("#videoModal .modal-header span")).click()
    // 11 | click | id=cartur | 
    await driver.findElement(By.id("cartur")).click()
    // 12 | assertText | css=.col-lg-8 > h2 | Products
    assert(await driver.findElement(By.css(".col-lg-8 > h2")).getText() == "Products")
    // 13 | click | css=.active > .nav-link | 
    await driver.findElement(By.css(".active > .nav-link")).click()
    // 14 | close |  | 
    await driver.close()
  })
})
