// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('browsing Category test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('browsing Category test', async function() {
    await driver.get("https://www.demoblaze.com/")
    await driver.manage().window().setRect({ width: 783, height: 816 })
    await driver.executeScript("window.scrollTo(0,104.80000305175781)")
    await driver.findElement(By.id("itemc")).click()
    {
      const elements = await driver.findElements(By.css(".col-md-6:nth-child(1)"))
      assert(elements.length)
    }
    await driver.findElement(By.linkText("Laptops")).click()
    {
      const elements = await driver.findElements(By.css(".col-md-6:nth-child(1)"))
      assert(elements.length)
    }
    await driver.findElement(By.linkText("Monitors")).click()
    {
      const elements = await driver.findElements(By.css(".col-md-6:nth-child(1)"))
      assert(elements.length)
    }
    await driver.close()
  })
})
