// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('check the added items and remove one test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('check the added items and remove one test', async function() {
    await driver.get("https://www.demoblaze.com/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css(".active > .nav-link")).click()
    await driver.findElement(By.css(".col-lg-4:nth-child(2) .card-img-top")).click()
    await driver.findElement(By.linkText("Add to cart")).click()
    assert(await driver.switchTo().alert().getText() == "Product added.")
    await driver.findElement(By.id("cartur")).click()
    await driver.wait(until.elementLocated(By.css("td:nth-child(2)")), 30000)
    await driver.findElement(By.linkText("Delete")).click()
    await driver.findElement(By.linkText("Cart")).click()
    {
      const elements = await driver.findElements(By.css("td:nth-child(2)"))
      assert(!elements.length)
    }
    await driver.close()
  })
})
