// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('order confirmation after payment test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('order confirmation after payment test', async function() {
    await driver.get("https://www.demoblaze.com/")
    await driver.manage().window().setRect({ width: 784, height: 816 })
    await driver.findElement(By.css(".col-lg-4:nth-child(1) .card-img-top")).click()
    await driver.findElement(By.linkText("Add to cart")).click()
    assert(await driver.switchTo().alert().getText() == "Product added.")
    await driver.findElement(By.id("cartur")).click()
    await driver.findElement(By.css(".btn-success")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("farah abdelkefi")
    await driver.findElement(By.id("country")).sendKeys("Tunisie")
    await driver.findElement(By.id("city")).sendKeys("sfax")
    await driver.findElement(By.id("card")).click()
    await driver.findElement(By.id("card")).sendKeys("1111111111")
    await driver.findElement(By.id("month")).click()
    await driver.findElement(By.id("month")).sendKeys("11")
    await driver.findElement(By.id("year")).click()
    await driver.findElement(By.id("year")).sendKeys("2015")
    await driver.findElement(By.css("#orderModal .btn-primary")).click()
    assert(await driver.findElement(By.css("h2:nth-child(6)")).getText() == "Thank you for your purchase!")
    await driver.findElement(By.css(".confirm")).click()
    await driver.close()
  })
})
