// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('HelloPageTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('HelloPageTest', async function() {
    await driver.get("https://safatelli.github.io/tp-test-logiciel/assets/hello.html")
    await driver.manage().window().setRect({ width: 784, height: 817 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("Intidhar_ben_hnia")
    await driver.findElement(By.css("button")).click()
    assert(await driver.findElement(By.id("message")).getText() == "Bonjour, Intidhar_ben_hnia !")
  })
})
